# Generated by Django 4.2.6 on 2023-11-06 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='polsChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='pulsMsgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='puls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('fchoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fch', to='pulse.polschoice')),
                ('schoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sch', to='pulse.polschoice')),
            ],
        ),
    ]
