# Generated by Django 4.2.6 on 2023-11-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pulsMsgs',
        ),
    ]
