# Generated by Django 4.2.6 on 2023-11-10 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0003_remove_puls_fchoice_remove_puls_schoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulsChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='puls',
            name='fchoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fch', to='pulse.pulschoice'),
        ),
        migrations.AddField(
            model_name='puls',
            name='schoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sch', to='pulse.pulschoice'),
        ),
    ]
