# Generated by Django 4.2.6 on 2023-11-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0007_alter_puls_winvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puls',
            name='winVote',
            field=models.IntegerField(default=0),
        ),
    ]
